In [1]:
import pandas as pd
import numpy as np
import os
os.getcwd()

'/home/dsxuser/work'

In [4]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_fee561139b3741cb9557e4db160e1832 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='CGpSDGdRcbRQr5hgo_7dkSijweyGKbxRsben4G04E6Kn',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_fee561139b3741cb9557e4db160e1832.get_object(Bucket='deeplearningprojects-donotdelete-pr-90fl5u3omzuyo7',Key='winequality-white.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body,delimiter=";")
df.head()



fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [5]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [6]:
x = df.iloc[:,0:11].values

In [7]:
y=df.iloc[:,11].values



In [8]:
x

array([[  7.  ,   0.27,   0.36, ...,   3.  ,   0.45,   8.8 ],
       [  6.3 ,   0.3 ,   0.34, ...,   3.3 ,   0.49,   9.5 ],
       [  8.1 ,   0.28,   0.4 , ...,   3.26,   0.44,  10.1 ],
       ..., 
       [  6.5 ,   0.24,   0.19, ...,   2.99,   0.46,   9.4 ],
       [  5.5 ,   0.29,   0.3 , ...,   3.34,   0.38,  12.8 ],
       [  6.  ,   0.21,   0.38, ...,   3.26,   0.32,  11.8 ]])

In [9]:
y






array([6, 6, 6, ..., 6, 7, 6])

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler  
sc=StandardScaler()
x_train = sc.fit_transform(x_train)  ## finding out the best value and transforming
x_test = sc.transform(x_test) 

In [12]:
from keras.utils import to_categorical
y_train = to_categorical(y_train)

Using TensorFlow backend.


In [13]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [14]:

model=Sequential()
model.add(Dense(10,input_dim=11))
model.add(Dense(100,activation = 'relu'))
model.add(Dense(100,activation = 'relu'))
model.add(Dense(100,activation = 'relu'))
model.add(Dense(10,activation = 'softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy']) 
       # for regression no need of activation function


In [15]:
model.fit(x_train,y_train,epochs= 100,batch_size=32)

Epoch 1/100
3918/3918 [==============================] - 1s 239us/step - loss: 1.3396 - acc: 0.4801
Epoch 2/100
3918/3918 [==============================] - 1s 206us/step - loss: 1.0911 - acc: 0.5408
Epoch 3/100
3918/3918 [==============================] - 1s 204us/step - loss: 1.0564 - acc: 0.5544
Epoch 4/100
3918/3918 [==============================] - 1s 206us/step - loss: 1.0358 - acc: 0.5620
Epoch 5/100
3918/3918 [==============================] - 1s 204us/step - loss: 1.0115 - acc: 0.5745
Epoch 6/100
3918/3918 [==============================] - 1s 203us/step - loss: 0.9923 - acc: 0.5817
Epoch 7/100
3918/3918 [==============================] - 1s 205us/step - loss: 0.9784 - acc: 0.5789
Epoch 8/100
3918/3918 [==============================] - 1s 184us/step - loss: 0.9625 - acc: 0.5909
Epoch 9/100
3918/3918 [==============================] - 1s 202us/step - loss: 0.9491 - acc: 0.5965
Epoch 10/100
3918/3918 [==============================] - 1s 203us/step - loss: 0.9304 - acc: 0.6064

3918/3918 [==============================] - 1s 201us/step - loss: 0.1716 - acc: 0.9438
Epoch 81/100
3918/3918 [==============================] - 1s 203us/step - loss: 0.1752 - acc: 0.9375
Epoch 82/100
3918/3918 [==============================] - 1s 204us/step - loss: 0.1495 - acc: 0.9507
Epoch 83/100
3918/3918 [==============================] - 1s 202us/step - loss: 0.1501 - acc: 0.9530
Epoch 84/100
3918/3918 [==============================] - 1s 183us/step - loss: 0.1547 - acc: 0.9497
Epoch 85/100
3918/3918 [==============================] - 1s 201us/step - loss: 0.1527 - acc: 0.9518
Epoch 86/100
3918/3918 [==============================] - 1s 203us/step - loss: 0.1428 - acc: 0.9546
Epoch 87/100
3918/3918 [==============================] - 1s 206us/step - loss: 0.1568 - acc: 0.9497
Epoch 88/100
3918/3918 [==============================] - 1s 201us/step - loss: 0.1660 - acc: 0.9433
Epoch 89/100
3918/3918 [==============================] - 1s 184us/step - loss: 0.1496 - acc: 0.9502
Epo

In [16]:
y_train

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [17]:
#y_pred = model.predict(x_train[0:1])

In [18]:
y_pred = model.predict_classes(x_train[0:1])

In [19]:
y_pred

array([5])

In [20]:
x_train[0:1]

array([[ 0.41960224, -0.18345438, -0.10617414,  0.80769346,  0.73339424,
        -0.73160893, -0.57903849,  0.88522816,  0.27871789, -0.0037976 ,
        -0.01506672]])

In [21]:
df.quality.value_counts()

6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: quality, dtype: int64

In [22]:
model.save("wine_quality.h5")

In [23]:
!tar -zcvf wine_quality.tgz wine_quality.h5

wine_quality.h5


In [24]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [25]:
wml_credentials = {
    "access_key":"NQwIDM3NeEfIQoBpKqSPOZQ6EGxzBVY0U0vYe6kSGJIr",
    "instance_id": "010cf8d0-4738-4f77-b380-f1e9b70da3e2",
    "password": "18dce468-8c59-48c3-82f2-de3cd105e1bf",
    "url": "https://eu-gb.ml.cloud.ibm.com",
    "username": "a95be078-3e88-422d-9394-cee3c9134cf7"
   
}

In [26]:
client = WatsonMachineLearningAPIClient(wml_credentials)

In [27]:
metadata = {
    client.repository.ModelMetaNames.NAME : "keras model",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES: [{'name':'keras','version': '2.1.3'}],
    client.repository.ModelMetaNames.FRAMEWORK_NAME : "tensorflow",
    client.repository.ModelMetaNames.FRAMEWORK_VERSION : "1.5",
}

In [28]:
model_details = client.repository.store_model(model="wine_quality.tgz",meta_props=metadata)

In [29]:
client.repository.list_models()

------------------------------------  -----------  ------------------------  --------------
GUID                                  NAME         CREATED                   FRAMEWORK
184bbce1-83a4-4ce0-b1c8-948fe4937097  keras model  2019-05-28T17:28:08.818Z  tensorflow-1.5
e9f3f2eb-5b5b-4b14-848f-9f4714f61789  keras model  2019-05-28T16:50:34.313Z  tensorflow-1.5
e7d80e18-a30c-4e5d-9161-2152ea65a93a  keras model  2019-05-17T10:19:32.949Z  tensorflow-1.5
2649b526-4cda-4393-abd5-e849d56f567b  keras model  2019-05-17T10:02:47.168Z  tensorflow-1.5
------------------------------------  -----------  ------------------------  --------------


In [30]:
model_uid = model_details['metadata']['guid']
model_deploy = client.deployments.create(artifact_uid=model_uid,name="wine-quality")



#######################################################################################

Synchronous deployment creation for uid: '184bbce1-83a4-4ce0-b1c8-948fe4937097' started

#######################################################################################


INITIALIZING
DEPLOY_IN_PROGRESS
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='7046a5e0-7daf-4d5f-aa91-8e80610df58d'
------------------------------------------------------------------------------------------------




In [31]:
scoring_endpoint = client.deployments.get_scoring_url(model_deploy)
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/010cf8d0-4738-4f77-b380-f1e9b70da3e2/deployments/7046a5e0-7daf-4d5f-aa91-8e80610df58d/online'

In [32]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36           20.70      0.045   
1               6.3             0.300         0.34            1.60      0.049   
2               8.1             0.280         0.40            6.90      0.050   
3               7.2             0.230         0.32            8.50      0.058   
4               7.2             0.230         0.32            8.50      0.058   
5               8.1             0.280         0.40            6.90      0.050   
6               6.2             0.320         0.16            7.00      0.045   
7               7.0             0.270         0.36           20.70      0.045   
8               6.3             0.300         0.34            1.60      0.049   
9               8.1             0.220         0.43            1.50      0.044   
10              8.1             0.270         0.41            1.45      0.033   
11              8.6             0.230         0.40            4.20      0.035   
12              7.9             0.180         0.37            1.20      0.040   
13              6.6             0.160         0.40            1.50      0.044   
14              8.3             0.420         0.62           19.25      0.040   
15              6.6             0.170         0.38            1.50      0.032   
16              6.3             0.480         0.04            1.10      0.046   
17              6.2             0.660         0.48            1.20      0.029   
18              7.4             0.340         0.42            1.10      0.033   
19              6.5             0.310         0.14            7.50      0.044   
20              6.2             0.660         0.48            1.20      0.029   
21              6.4             0.310         0.38            2.90      0.038   
22              6.8             0.260         0.42            1.70      0.049   
23              7.6             0.670         0.14            1.50      0.074   
24              6.6             0.270         0.41            1.30      0.052   
25              7.0             0.250         0.32            9.00      0.046   
26              6.9             0.240         0.35            1.00      0.052   
27              7.0             0.280         0.39            8.70      0.051   
28              7.4             0.270         0.48            1.10      0.047   
29              7.2             0.320         0.36            2.00      0.033   
...             ...               ...          ...             ...        ...   
4868            5.8             0.230         0.31            4.50      0.046   
4869            6.6             0.240         0.33           10.10      0.032   
4870            6.1             0.320         0.28            6.60      0.021   
4871            5.0             0.200         0.40            1.90      0.015   
4872            6.0             0.420         0.41           12.40      0.032   
4873            5.7             0.210         0.32            1.60      0.030   
4874            5.6             0.200         0.36            2.50      0.048   
4875            7.4             0.220         0.26            1.20      0.035   
4876            6.2             0.380         0.42            2.50      0.038   
4877            5.9             0.540         0.00            0.80      0.032   
4878            6.2             0.530         0.02            0.90      0.035   
4879            6.6             0.340         0.40            8.10      0.046   
4880            6.6             0.340         0.40            8.10      0.046   
4881            5.0             0.235         0.27           11.75      0.030   
4882            5.5             0.320         0.13            1.30      0.037   
4883            4.9             0.470         0.17            1.90      0.035   
4884            6.5             0.330         0.38            8.30      0.048   
4885            6.6             0.340