In [1]:
import pandas as pd
import numpy as np
import os
os.getcwd()

'E:\\SIP Hackathon'

In [2]:
df = pd.read_csv(r"E:\SIP Hackathon\winequality-white.csv")

In [3]:
df.head()

fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0   7;0.27;0.36;20.7;0.045;45;170;1.001;3;0.45;8.8;6                                                                                                                     
1  6.3;0.3;0.34;1.6;0.049;14;132;0.994;3.3;0.49;9...                                                                                                                     
2  8.1;0.28;0.4;6.9;0.05;30;97;0.9951;3.26;0.44;1...                                                                                                                     
3  7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4...                                                                                                                     
4  7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4...

In [4]:
from __future__ import division

In [5]:

def loadDataset(data_path):
    return pd.read_csv(data_path, delimiter = ';', encoding='utf-8')

In [6]:
df = loadDataset("E:\SIP Hackathon\winequality-white.csv")
df.shape


(4898, 12)

In [7]:
x = df.iloc[:,0:11].values

In [8]:
y=df.iloc[:,11].values



In [9]:
x

array([[ 7.  ,  0.27,  0.36, ...,  3.  ,  0.45,  8.8 ],
       [ 6.3 ,  0.3 ,  0.34, ...,  3.3 ,  0.49,  9.5 ],
       [ 8.1 ,  0.28,  0.4 , ...,  3.26,  0.44, 10.1 ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  2.99,  0.46,  9.4 ],
       [ 5.5 ,  0.29,  0.3 , ...,  3.34,  0.38, 12.8 ],
       [ 6.  ,  0.21,  0.38, ...,  3.26,  0.32, 11.8 ]])

In [10]:
y






array([6, 6, 6, ..., 6, 7, 6], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler  
sc=StandardScaler()
x_train = sc.fit_transform(x_train)  ## finding out the best value and transforming
x_test = sc.transform(x_test) 

In [13]:
from keras.utils import to_categorical
y_train = to_categorical(y_train)

Using TensorFlow backend.


In [14]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [15]:

model=Sequential()
model.add(Dense(10,input_dim=11))
model.add(Dense(100,activation = 'relu'))
model.add(Dense(100,activation = 'relu'))
model.add(Dense(100,activation = 'relu'))
model.add(Dense(10,activation = 'softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy']) 
       # for regression no need of activation function


Instructions for updating:
Colocations handled automatically by placer.


In [16]:
model.fit(x_train,y_train,epochs=100,batch_size=32)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
3918/3918 [==============================] - 1s 335us/step - loss: 1.3009 - acc: 0.5013
Epoch 2/100
3918/3918 [==============================] - 0s 109us/step - loss: 1.0856 - acc: 0.5510
Epoch 3/100
3918/3918 [==============================] - 0s 104us/step - loss: 1.0509 - acc: 0.5607
Epoch 4/100
3918/3918 [==============================] - 0s 80us/step - loss: 1.0375 - acc: 0.5536
Epoch 5/100
3918/3918 [==============================] - 0s 99us/step - loss: 1.0105 - acc: 0.5664
Epoch 6/100
3918/3918 [==============================] - 0s 83us/step - loss: 0.9957 - acc: 0.5784
Epoch 7/100
3918/3918 [==============================] - 0s 87us/step - loss: 0.9817 - acc: 0.5827
Epoch 8/100
3918/3918 [==============================] - 0s 94us/step - loss: 0.9676 - acc: 0.5883
Epoch 9/100
3918/3918 [==============================] - 0s 81us/step - loss: 0.9538 - acc: 0.5794
Epoch 10/100
3918/3918 [==============================] - 

3918/3918 [==============================] - 0s 93us/step - loss: 0.2244 - acc: 0.9245
Epoch 80/100
3918/3918 [==============================] - 0s 101us/step - loss: 0.2242 - acc: 0.9140
Epoch 81/100
3918/3918 [==============================] - 0s 92us/step - loss: 0.2112 - acc: 0.9234
Epoch 82/100
3918/3918 [==============================] - 0s 104us/step - loss: 0.1902 - acc: 0.9339
Epoch 83/100
3918/3918 [==============================] - 0s 112us/step - loss: 0.1969 - acc: 0.9319
Epoch 84/100
3918/3918 [==============================] - 0s 101us/step - loss: 0.2004 - acc: 0.9290
Epoch 85/100
3918/3918 [==============================] - 0s 103us/step - loss: 0.1804 - acc: 0.9390
Epoch 86/100
3918/3918 [==============================] - 0s 106us/step - loss: 0.2034 - acc: 0.9265
Epoch 87/100
3918/3918 [==============================] - 0s 104us/step - loss: 0.1801 - acc: 0.9382
Epoch 88/100
3918/3918 [==============================] - 0s 111us/step - loss: 0.1672 - acc: 0.9393
Epoch

In [17]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [18]:
y_pred = model.predict(x_train[0:1])

In [19]:
y_pred = model.predict_classes(x_train[0:1])

In [20]:
y_pred

array([5], dtype=int64)

In [21]:
x_train[0:1]

array([[ 0.41960224, -0.18345438, -0.10617414,  0.80769346,  0.73339424,
        -0.73160893, -0.57903849,  0.88522816,  0.27871789, -0.0037976 ,
        -0.01506672]])

In [22]:
df.quality.value_counts()

6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: quality, dtype: int64

In [23]:
test = [[6.2,0.35,0.03,1.2,0.064,29,120,0.9934,3.22,0.54,9.1]]

In [24]:
test1 = np.array(test)
test1

array([[6.200e+00, 3.500e-01, 3.000e-02, 1.200e+00, 6.400e-02, 2.900e+01,
        1.200e+02, 9.934e-01, 3.220e+00, 5.400e-01, 9.100e+00]])

In [25]:
y_pred = model.predict(test1)

In [26]:
y_pred

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.2297145e-10,
        0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)